import type { Metadata } from "next";
import { Bitter, Dosis } from "next/font/google";

import "./globals.css";
import QueryProvider from "@/lib/QueryProvider";

const dosis = Dosis({ subsets: ["latin"] });
const bitter = Bitter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dosis.className} ${bitter.className} antialiased`}>
        <QueryProvider> {children}</QueryProvider>
      </body>
    </html>
  );
}
